services:
  redis:
    image: redis
    container_name: redis-local
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no

  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-local
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=123456
      - ORACLE_DATABASE=MYPDB
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data:
