apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: auth-service
type: Opaque
data:
  db-username: c3lzdGVt
  db-password: MTIzNDU2
  jwt-secret: QUFrMWtrRHZkazE4VnNXMVpwYVd6ek5HUmtMdzVzSQ==
